name: Build, Test, and Deploy Laravel with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Laravel Containers
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: your-dockerhub-username/laravel-app
      DOCKER_IMAGE_NGINX: your-dockerhub-username/laravel-nginx

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up PHP environment for tests
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo_mysql
          tools: composer

      # Install dependencies
      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --optimize-autoloader

      # Set up Docker Buildx for building images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Laravel PHP image
      - name: Build Laravel PHP Image
        run: |
          docker build -t $DOCKER_IMAGE:latest -f Dockerfile .

      # Build the Nginx image
      - name: Build Nginx Image
        run: |
          docker build -t $DOCKER_IMAGE_NGINX:latest -f ./docker/nginx/Dockerfile .

      # Run Laravel Tests
      - name: Run Laravel Tests
        run: |
          docker-compose -f docker-compose.yml up -d mysql
          docker-compose -f docker-compose.yml run --rm app php artisan test --env=testing
          docker-compose -f docker-compose.yml down

      # Run Larastan (Static Analysis)
      - name: Run Larastan
        run: |
          ./vendor/bin/phpstan analyse --level=max app

      # Push the Laravel PHP image to Docker Hub
      - name: Push Laravel PHP Image
        run: |
          docker push $DOCKER_IMAGE:latest

      # Push the Nginx image to Docker Hub
      - name: Push Nginx Image
        run: |
          docker push $DOCKER_IMAGE_NGINX:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      # SSH into server and deploy
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/laravel-app:latest
            docker pull your-dockerhub-username/laravel-nginx:latest
            docker-compose -f /path/to/docker-compose.yml up -d
